-- Schema de Base de Datos para STEL Bolivia
-- Copia y ejecuta este script en el "SQL Editor" de tu proyecto de Supabase.

-- Habilitar extensión para UUIDs si no está habilitada
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TABLA: clientes
CREATE TABLE IF NOT EXISTS public.clientes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo_protegido VARCHAR(50) UNIQUE NOT NULL,
    nombre_completo VARCHAR(255) NOT NULL,
    ci VARCHAR(50) NOT NULL,
    telefono VARCHAR(50) NOT NULL,
    nit VARCHAR(50),
    direccion TEXT NOT NULL,
    estado_cuenta VARCHAR(50) NOT NULL DEFAULT 'Sin plan', -- 'Al día', 'Deudor', 'Suspendido', 'Sin plan', 'Pendiente'
    proxima_factura DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS (Row Level Security) para clientes
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;

-- Crear políticas públicas sencillas para permitir lectura y escritura desde la app (Anonymous)
CREATE POLICY "Permitir lectura pública de clientes" ON public.clientes
    FOR SELECT USING (true);

CREATE POLICY "Permitir inserción pública de clientes" ON public.clientes
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Permitir actualización pública de clientes" ON public.clientes
    FOR UPDATE USING (true);


-- 2. TABLA: servicios_contratados
CREATE TABLE IF NOT EXISTS public.servicios_contratados (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cliente_id UUID REFERENCES public.clientes(id) ON DELETE CASCADE,
    tipo_servicio VARCHAR(50) NOT NULL, -- 'Internet', 'Televisión', 'Combo'
    plan_nombre VARCHAR(100) NOT NULL, -- 'Básico', 'Intermedio', 'Avanzado', 'Combo Esencial', etc.
    velocidad_mbps INTEGER,
    canales_tv INTEGER,
    precio_mensual NUMERIC(10, 2) NOT NULL,
    pantallas_adicionales INTEGER DEFAULT 0,
    ip_publica BOOLEAN DEFAULT FALSE,
    estado VARCHAR(50) NOT NULL DEFAULT 'Activo', -- 'Activo', 'Suspendido', 'Inactivo'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.servicios_contratados ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir lectura pública de servicios" ON public.servicios_contratados
    FOR SELECT USING (true);

CREATE POLICY "Permitir inserción pública de servicios" ON public.servicios_contratados
    FOR INSERT WITH CHECK (true);


-- 3. TABLA: solicitudes_planes
CREATE TABLE IF NOT EXISTS public.solicitudes_planes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    plan_nombre VARCHAR(100) NOT NULL,
    tipo_servicio VARCHAR(50) NOT NULL,
    precio_mensual NUMERIC(10, 2) NOT NULL,
    nombre_cliente VARCHAR(255) NOT NULL,
    telefono VARCHAR(50) NOT NULL,
    ci VARCHAR(50) NOT NULL,
    nit VARCHAR(50),
    direccion TEXT NOT NULL,
    pantallas_adicionales INTEGER DEFAULT 0,
    ip_publica BOOLEAN DEFAULT FALSE,
    comprobante_url TEXT, -- Almacena base64 o referencia de la imagen de pago
    codigo_usuario_generado VARCHAR(50),
    estado VARCHAR(50) NOT NULL DEFAULT 'Pendiente', -- 'Pendiente', 'Aprobado', 'Rechazado'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.solicitudes_planes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir lectura pública de solicitudes" ON public.solicitudes_planes
    FOR SELECT USING (true);

CREATE POLICY "Permitir inserción pública de solicitudes" ON public.solicitudes_planes
    FOR INSERT WITH CHECK (true);


-- 4. TABLA: comunicados
CREATE TABLE IF NOT EXISTS public.comunicados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    resumen TEXT NOT NULL,
    contenido TEXT NOT NULL,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    autor VARCHAR(100) NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.comunicados ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir lectura pública de comunicados" ON public.comunicados
    FOR SELECT USING (true);

CREATE POLICY "Permitir inserción pública de comunicados" ON public.comunicados
    FOR INSERT WITH CHECK (true);


-- =========================================================================
-- DATOS SEMILLA (MOCK DATA) DE EJEMPLO PARA PRUEBAS
-- =========================================================================

-- Insertar Clientes de Prueba
INSERT INTO public.clientes (id, codigo_protegido, nombre_completo, ci, telefono, nit, direccion, estado_cuenta, proxima_factura)
VALUES 
('a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d', 'STL-12345', 'Carlos Mendoza Torrico', '8439281 LP', '+591 71234567', '8439281012', 'Av. Arce, Edificio Multicentro, Piso 10, La Paz', 'Al día', CURRENT_DATE + INTERVAL '15 days'),
('b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e', 'STL-98765', 'Valeria Rojas Benitez', '9204821 SC', '+591 76543210', NULL, 'Condominio Sevilla, Casa 24, Zona Norte, Santa Cruz', 'Deudor', CURRENT_DATE - INTERVAL '2 days'),
('c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f', 'STL-VISIT', 'Andres Lopez Cuentas', '1029384 CB', '+591 70112233', NULL, 'Av. America Oeste #123, Cochabamba', 'Sin plan', NULL)
ON CONFLICT (codigo_protegido) DO NOTHING;

-- Insertar Servicios Contratados de Prueba
INSERT INTO public.servicios_contratados (cliente_id, tipo_servicio, plan_nombre, velocidad_mbps, canales_tv, precio_mensual, pantallas_adicionales, ip_publica, estado)
VALUES
('a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d', 'Combo', 'Combo Intermedio', 200, 2, 309.00, 2, FALSE, 'Activo'), -- Total: 309 + 2*30 = 369 Bs
('b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e', 'Internet', 'Avanzado', 200, 0, 250.00, 0, TRUE, 'Activo') -- Total: 250 + 249 = 499 Bs
ON CONFLICT DO NOTHING;

-- Insertar Comunicados de Prueba (idénticos a los estáticos iniciales)
INSERT INTO public.comunicados (titulo, resumen, contenido, autor, categoria)
VALUES
('Incremento de Velocidad en Planes de Internet', 'STEL Bolivia anuncia mejora significativa en todos sus planes de internet residencial sin costo adicional para los clientes.', 'Nos complace informar a nuestros clientes que a partir del 1 de junio de 2024, todos los planes de internet residencial experimentarán un incremento automático en su velocidad de navegación. Los planes Básico pasan de 10Mbps a 15Mbps, Profesional de 50Mbps a 75Mbps, y Premium de 100Mbps a 150Mbps. Esta mejora se aplicará de forma automática sin necesidad de realizar ningún trámite adicional. Agradecemos la confianza depositada en nuestros servicios y reafirmamos nuestro compromiso con la calidad y la innovación tecnológica.', 'Dirección de Tecnología', 'Servicios'),
('Expansión de Red de Fibra Óptica', 'STEL Bolivia expande su infraestructura de fibra óptica a nuevas zonas metropolitanas.', 'STEL Bolivia anuncia la expansión de su red de fibra óptica a los municipios de El Alto, Viacha y Sacaba. Esta expansión permitirá ofrecer servicios de internet de alta velocidad a más de 50,000 nuevos hogares y negocios. Las zonas beneficiadas incluirán cobertura 100% fibra óptica con velocidades simétricas de hasta 500Mbps. Se estima que la implementación se complete en un período de 6 meses, priorizando las áreas con mayor demanda.', 'Gerencia de Infraestructura', 'Infraestructura'),
('Mantenimiento Programado de Red', 'Se realizará mantenimiento preventivo en la red troncal durante el próximo fin de semana.', 'Con el objetivo de garantizar la calidad y estabilidad de nuestros servicios, se realizará un mantenimiento programado de la red troncal el sábado 25 de mayo de 22:00 a 06:00 horas. Durante este período, algunos servicios podrían presentar interrupciones intermitentes. Se recomienda a los clientes planificar sus actividades en consecuencia. Las zonas afectadas incluyen: Zona Sur, Zona Central y parte de la Zona Norte. Disculpen las molestias ocasionadas.', 'Departamento de Operaciones', 'Mantenimiento'),
('Nueva Plataforma de Atención al Cliente', 'Lanzamos nuestra nueva plataforma digital para atención al cliente las 24 horas.', 'STEL Bolivia presenta su nueva plataforma de atención al cliente basada en inteligencia artificial. Ahora puedes realizar consultas, reportar fallas y gestionar tus servicios a través de nuestro chat web, disponible 24/7. Además, nuestra nueva app móvil incluye funcionalidades avanzadas como autodiagnóstico de red, gestión de pagos y soporte técnico remoto. Descarga la app desde Google Play o App Store.', 'Innovación Digital', 'Novedades'),
('Promoción Aniversario STEL', 'Celebramos nuestro aniversario con descuentos especiales en paquetes combinados.', 'En conmemoración de nuestro 15 aniversario, ofrecemos descuentos exclusivos del 30% en todos nuestros paquetes combinados de internet y televisión durante el mes de junio. Además, los nuevos clientes recibirán 3 meses adicionales sin costo en servicios de streaming. No pierdas esta oportunidad única y contacta a nuestros asesores comerciales para más información.', 'Marketing STEL', 'Promociones')
ON CONFLICT DO NOTHING;
